force-app/main/default/objects/Limit_Types__mdt/Limit_Types__mdt.object-meta.xml
<CustomObject>
    <label>Limit Types</label>
    <pluralLabel>Limit Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limit_Types__mdt/fields/Limit_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Limit_Type_Name__c</fullName>
    <label>Limit Type Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrgLimitsHandlerTest.cls
@isTest
public class OrgLimitsHandlerTest {
    
    @isTest static void testSetCalloutData(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        OrgLimitsHandler limtHandler = new OrgLimitsHandler();
        List<Limit_Types__mdt> limitTypeMdt = [SELECT Id, Limit_Type_Name__c FROM Limit_Types__mdt LIMIT 1];
        limtHandler.OrgLimitsHandler();
        
        
        
    }

}